#!/usr/bin/env python3
"""
scaffold.py - ensure standard project files exist.

Behavior: create if missing, never overwrite if present.
  - .gitignore     -> default Python/DEVKIT ignores
  - pyproject.toml -> minimal skeleton (dependencies left empty to fill)
  - .git           -> git init when git is available and no repo exists
"""

import shutil
import subprocess
from pathlib import Path

DEFAULT_GITIGNORE = """\
# DEVKIT
.devkit/

# Python
__pycache__/
*.py[cod]
*.egg-info/
.venv/
venv/
env/
dist/
build/

# IDE
.vscode/
.idea/
"""


def _sanitize_name(name: str) -> str:
    return name.strip().lower().replace(" ", "-")


def _pyproject_skeleton(name: str) -> str:
    return """\
[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "%s"
version = "0.1.0"
description = "%s - generated by DEVKIT"
requires-python = ">=3.9"
dependencies = [
]
""" % (name, name)


def ensure_gitignore(root: Path) -> str:
    p = root / ".gitignore"
    if p.exists():
        return "exists"
    p.write_text(DEFAULT_GITIGNORE, encoding="utf-8")
    return "created"


def ensure_pyproject(root: Path, name: str) -> str:
    p = root / "pyproject.toml"
    if p.exists():
        return "exists"
    p.write_text(_pyproject_skeleton(_sanitize_name(name)), encoding="utf-8")
    return "created"


def ensure_git(root: Path) -> str:
    if (root / ".git").exists():
        return "exists"
    if shutil.which("git") is None:
        return "skipped (git not found)"
    try:
        subprocess.run(["git", "init"], cwd=str(root), capture_output=True, check=True)
        return "initialized"
    except Exception:
        return "skipped (git init failed)"


def scaffold(root: Path, name: str) -> dict:
    root = Path(root)
    return {
        ".gitignore": ensure_gitignore(root),
        "pyproject.toml": ensure_pyproject(root, name),
        ".git": ensure_git(root),
    }
